/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import classes.conexao;
import static classes.conexao.statement;
import classes.estacoes;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author Aluno
 */
public class bilhete extends javax.swing.JFrame {
 String tipo="", dbData, dbHora;
    int maxSenha=0, seq=0;
    conexao comb = new conexao();
        Date dataHora = new Date();
    
    public bilhete() {
       
        
        initComponents();
        

    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbestacao = new javax.swing.JComboBox();
        lbbilhete = new javax.swing.JLabel();
        txtterminal = new javax.swing.JTextField();
        lbvalor = new javax.swing.JLabel();
        lbImg = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbmensagem = new javax.swing.JLabel();
        lbtickt = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbhora = new javax.swing.JLabel();
        lbdata = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel1.setText("Atibaia");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 80, 30));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setText("Geração de bilhete unico");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setText("Estação");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 41, 65, 34));

        jButton1.setBackground(new java.awt.Color(0, 51, 204));
        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Emitir");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, -1, -1));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel4.setText("Terminal");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 93, 65, 24));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setText("Bilhete");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 136, 65, 24));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel6.setText("Valor");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 65, 24));

        cbestacao.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        getContentPane().add(cbestacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 46, 120, -1));

        lbbilhete.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        getContentPane().add(lbbilhete, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 136, 94, 24));

        txtterminal.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtterminal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtterminalActionPerformed(evt);
            }
        });
        getContentPane().add(txtterminal, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 93, 120, -1));

        lbvalor.setText("4.00");
        getContentPane().add(lbvalor, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 94, 27));
        getContentPane().add(lbImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 160, 160));

        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 590, 90));

        lbmensagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/metr.png"))); // NOI18N
        getContentPane().add(lbmensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 460, 600, 80));

        lbtickt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lbtickt, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 160, 370));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 160, 20));

        lbhora.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(lbhora, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 90, 30));

        lbdata.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(lbdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 90, 30));

        setSize(new java.awt.Dimension(607, 580));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtterminalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtterminalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtterminalActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
                    letreiro();
        
                    
                    
                    {  ImageIcon imagem = new  ImageIcon(bilhete.class.getResource("/img/metro.png"));
        
   Image imag = imagem.getImage().getScaledInstance(lbImg.getWidth(), lbImg.getHeight(), Image.SCALE_DEFAULT);
        
    lbImg.setIcon(new ImageIcon(imag));}
    
    
      //  ImageIcon imagem = new  ImageIcon(bilhete.class.getResource("/img/metr.png"));
        
   //Image imag = imagem.getImage().getScaledInstance(lbmensagem.getWidth(), lbmensagem.getHeight(), Image.SCALE_DEFAULT);
        
   // lbmensagem.setIcon(new ImageIcon(imag));
    
    
        Date dataHora = new Date();
        SimpleDateFormat dt = new SimpleDateFormat("dd/MM/yyyy");
        lbdata.setText(dt.format(dataHora));
 
        Timer timer = new Timer(1000, new dataHora());
        timer.start();
        carregaEstacao();
    }//GEN-LAST:event_formWindowOpened

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
   
         pegaSenha();
           geraSenha();
       
    }//GEN-LAST:event_jButton1MouseClicked

     private void geraSenha() {
        lbtickt.setVisible(true);
        lbtickt.setText("<html><br><p style='font-size:5px; "
                + "text-align:center'>=======================</p><br><p "
                + "text-align:center'>COMPROVANTE DE VENDA</p><br><p "
                + "text-align:center'>=======================</p><br><p "
                + "text-align:center'>BILHETE UNITÁRIO</p><br><p "
                + "text-align:center'>ESTAÇÃO: "+cbestacao.getSelectedItem()+"</p><br><p "
                + "text-align:center'>=======================</p><br><p "
                + "text-align:center'>NUMERO: "+seq+"</p><br><p "      
                + "text-align:center'>TERMINAL: "+txtterminal.getText()+"</p><br><p "    
                + "text-align:center'>VALOR: R$4,00</p><br><p "      
                + "text-align:center'>=======================</p><br><p " 
                + "text-align:center'>ATENÇÃO! VALIDO APENAS PARA UMA VIAGEM</p><br><p "    
                + "text-align:center'>UTILIZAR O BILHETE EM ATÉ 72 HORAS</p><br><p "            
                + "style='font-size:5px; text-align:center'>"
                + "DATA:"+lbdata .getText()+"</p><br>"
                + "<p style='font-size:5px; text-align:center'>HORA:"
                + lbhora.getText()+ "</p><html>");;
        movimento();
    }
    
    
    public void letreiro()
    {
        new Thread(){
            public void run(){ 
                int y = 450;
                int x = 590;
                
                while(true){
                    if(x >-590){
                        lbmensagem.setLocation(x,y);
                        
                        x--; 
                        }
                    else{
                        x = 600;
                    }
                    try{
                        sleep(4);
                    }catch (Exception e){
                    }
                }
            }            
        }.start();
    }
    
    
    public void movimento()
    {
        new Thread()
        {
            public void run()
            { 

               int x = 410;
               int y = 0;
               
                while(true)
                {
                    if( y < 140 )
                    {
                        y = y+1; 
                        lbtickt.setLocation(x , y);  
                    }
                    try
                    {
                        sleep(6);
                    }
                    catch (Exception e)
                    {
                    }
                }
            }
            
        }.start();
    }

    private void pegaSenha() {
        
         String sql = "Select max(tb03_cod_bilhete) from tb03_bilhete";
         
            
        try{

         int maxSenha = 0;
      
                
        conexao objetoBD = new conexao();
          
        
         seq = 0;
        objetoBD.conectar(); 
        ResultSet rs = statement.executeQuery(sql);  
       
        while (rs.next()) 
        {
             maxSenha = rs.getInt(1);
        }
        
        seq = maxSenha + 1; 
        
        
        objetoBD.desconectar();
        }
        catch (Exception e){
             System.out.println(e.getMessage());
         }
    }
    
    
    class dataHora implements ActionListener 
         {
           @Override
           public void actionPerformed(ActionEvent ae) 
          {
             Calendar now = Calendar.getInstance();
             lbhora.setText(String.format("%1$tH:%1$tM:%1$tS", now));
             
          }
       }
    
     private void gravaBanco()
    {
        //dbHora = (String.format("%1$tH:%1$tM:%1$tS", now));
        SimpleDateFormat dt = new SimpleDateFormat("yyyy-MM-dd");
        dbData = dt.format(dataHora);
        
        String sql = "insert into tb03_bilhete values (";
              // sql+=" '" +  + "','4', " + txtterminal + ",'" + dbData + "','" + dbHora + "','" + seq + "')";
               
              
        try{

        comb.conectar();
        
       int qtdreg = conexao.runSQL(sql);

        comb.desconectar();
        
        }
        catch (Exception e){
             System.out.println(e.getMessage());
        }
    }
    
     
          private void carregaEstacao()
    {
           try 
        {              
              cbestacao.removeAllItems();

              String sql = "SELECT * FROM tb02_estacao"; 
              comb.conectar();
       
              ResultSet rs = statement.executeQuery(sql);
        
              int id = 0;
              String nom = null;
        
              cbestacao.addItem(new estacoes(id, nom)); 
        
              while (rs.next())
              {
                id = rs.getInt("tb02_cod_estacao");  
                nom = rs.getString("tb02_descricao");  
                cbestacao.addItem(new estacoes(id, nom)); 
              }
              
              comb.desconectar();
              statement.close(); 
        }
               
        catch (Exception e)
        {
           System.out.println(e.getMessage());
        } 
       
    }
    
      
     
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bilhete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bilhete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bilhete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bilhete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bilhete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbestacao;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbImg;
    private javax.swing.JLabel lbbilhete;
    private javax.swing.JLabel lbdata;
    private javax.swing.JLabel lbhora;
    private javax.swing.JLabel lbmensagem;
    private javax.swing.JLabel lbtickt;
    private javax.swing.JLabel lbvalor;
    private javax.swing.JTextField txtterminal;
    // End of variables declaration//GEN-END:variables
}
